### ISSUE TITLE
error on execute /vendor/bin/pimcore-install 

### ISSUE THREAD

**Issue by choppe3766** [StefanieD/pimcore-docker-setup#1]
Hi, first of all thank for your great work :)

If I try to install pimcore i get the following error:

`* Warning: Declaration of Pimcore\Bundle\CoreBundle\EventListener\LegacyTemplateListener::onKernelView(Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent $event) should be compatible with Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener::onKernelView(Symfony\Component\HttpKernel\Event\KernelEvent $event)`

and the install script stops on 50%.

Could this be an issue with the latest pimcore 6 version, because pimcore has changed the symfony version from 3 to 4.

Thanks
Chris

**Comment by StefanieD** [comment]
Hi Chris,

thx for testing my setup scripts.
I could reproduce the error and I think you're right. Pimcore needs to update the LegacyTemplateListener.

As a workaround you can fix it with update the `composer.json` file and require an older version of the `sensio/framework-extra-bundle`. 
After running the initial create-project command you need to add the following line to the `pimcore/composer.json` file:

```
"require": {
    "php": ">=7.2",
    "wikimedia/composer-merge-plugin": "^1.4",
    "pimcore/pimcore": "~6.0.0",
    "sensio/framework-extra-bundle": "5.3.1"
  },
```

Then run a `composer update` and the install command should work.

Hope this help.

Thanks
Stefanie
