### ISSUE TITLE
Docker - nginx folder does not exist inside /etc

### ISSUE THREAD

**Issue by alex-w0** [StefanieD/pimcore-docker-setup#3]
According to your docker-compose.yml the site.conf (inside the service nginx) will be pasted to the path "/etc/nginx/conf.d/default.conf".
```
services:
    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/config/site.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
        networks:
            - pimcorenet
```
My problem is now that no folder with the name nginx exists within the directory /etc and consequently the document root and other stuff is mapped wrong.
```
drwxr-xr-x 1 root root    4096 Aug 21 19:31 .
drwxr-xr-x 1 root root    4096 Aug 21 19:30 ..
-rw------- 1 root root       0 Aug 12 00:00 .pwd.lock
-rw-r--r-- 1 root root    2981 Aug 12 00:00 adduser.conf
drwxr-xr-x 1 root root    4096 Aug 21 19:26 alternatives
drwxr-xr-x 3 root root    4096 Aug 21 19:26 apache2
drwxr-xr-x 1 root root    4096 Aug 12 00:00 apt
-rw-r--r-- 1 root root    1994 Apr 18 04:12 bash.bashrc
drwxr-xr-x 2 root root    4096 Aug 21 19:26 bash_completion.d
-rw-r--r-- 1 root root     367 Mar  2  2018 bindresvport.blacklist
drwxr-xr-x 3 root root    4096 Aug 14 07:30 ca-certificates
-rw-r--r-- 1 root root    5713 Aug 14 07:31 ca-certificates.conf
drwxr-xr-x 2 root root    4096 Aug 12 00:00 cron.daily
-rw-r--r-- 1 root root    2969 Feb 26 09:30 debconf.conf
-rw-r--r-- 1 root root       5 Apr 19 11:00 debian_version
drwxr-xr-x 1 root root    4096 Aug 21 19:31 default
-rw-r--r-- 1 root root     604 Jun 26  2016 deluser.conf
drwxr-xr-x 1 root root    4096 Aug 14 07:31 dpkg
drwxr-xr-x 3 root root    4096 Aug 14 07:30 emacs
-rw-r--r-- 1 root root       0 Aug 12 00:00 environment
drwxr-xr-x 4 root root    4096 Aug 21 19:31 fonts
-rw-r--r-- 1 root root      37 Aug 12 00:00 fstab
-rw-r--r-- 1 root root    2584 Aug  1  2018 gai.conf
-rw-r--r-- 1 root root     446 Aug 12 00:00 group
-rw-r--r-- 1 root root     446 Aug 12 00:00 group-
-rw-r----- 1 root shadow   374 Aug 12 00:00 gshadow
drwxr-xr-x 3 root root    4096 Aug 14 07:30 gss
-rw-r--r-- 1 root root       9 Aug  7  2006 host.conf
-rw-r--r-- 1 root root      13 Aug 21 19:30 hostname
-rw-r--r-- 1 root root     174 Aug 21 19:30 hosts
drwxr-xr-x 1 root root    4096 Aug 21 19:31 init.d
-rw-r--r-- 1 root root    1748 May  5  2018 inputrc
-rw-r--r-- 1 root root      27 May 13 20:25 issue
-rw-r--r-- 1 root root      20 May 13 20:25 issue.net
drwxr-xr-x 3 root root    4096 May 28 14:40 kernel
-rw-r--r-- 1 root root   17842 Aug 21 19:31 ld.so.cache
-rw-r--r-- 1 root root      34 Mar  2  2018 ld.so.conf
drwxr-xr-x 2 root root    4096 Aug 12 00:00 ld.so.conf.d
drwxr-xr-x 2 root root    4096 Aug 14 07:31 ldap
-rw-r--r-- 1 root root     191 Apr 25 14:47 libaudit.conf
drwxr-xr-x 4 root root    4096 Aug 21 19:26 lighttpd
lrwxrwxrwx 1 root root      27 Aug 12 00:00 localtime -> /usr/share/zoneinfo/Etc/UTC
-rw-r--r-- 1 root root   10477 Jul 27  2018 login.defs
drwxr-xr-x 1 root root    4096 Aug 21 19:31 logrotate.d
-rw-r--r-- 1 root root      33 Aug 12 00:00 machine-id
-rw-r--r-- 1 root root     111 Mar  2 07:05 magic
-rw-r--r-- 1 root root     111 Mar  2 07:05 magic.mime
-rw-r--r-- 1 root root     812 Dec 16  2018 mke2fs.conf
-rw-r--r-- 1 root root     286 May 13 20:25 motd
lrwxrwxrwx 1 root root      12 Aug 21 19:30 mtab -> /proc/mounts
drwxr-xr-x 4 root root    4096 Aug 21 19:26 mysql
drwxr-xr-x 8 root root    4096 Aug 21 19:31 nginx
-rw-r--r-- 1 root root     494 Feb 10  2019 nsswitch.conf
drwxr-xr-x 2 root root    4096 Aug 12 00:00 opt
lrwxrwxrwx 1 root root      21 May 13 20:25 os-release -> ../usr/lib/os-release
-rw-r--r-- 1 root root     552 Feb 14  2019 pam.conf
drwxr-xr-x 2 root root    4096 Aug 12 00:00 pam.d
-rw-r--r-- 1 root root     926 Aug 12 00:00 passwd
-rw-r--r-- 1 root root     926 Aug 12 00:00 passwd-
drwxr-xr-x 4 root root    4096 Aug 14 07:30 perl
-rw-r--r-- 1 root root     767 Mar  4  2016 profile
drwxr-xr-x 2 root root    4096 May 13 20:25 profile.d
drwxr-xr-x 1 root root    4096 Aug 21 19:31 rc0.d
drwxr-xr-x 1 root root    4096 Aug 21 19:31 rc1.d
drwxr-xr-x 1 root root    4096 Aug 21 19:31 rc2.d
drwxr-xr-x 1 root root    4096 Aug 21 19:31 rc3.d
drwxr-xr-x 1 root root    4096 Aug 21 19:31 rc4.d
drwxr-xr-x 1 root root    4096 Aug 21 19:31 rc5.d
drwxr-xr-x 1 root root    4096 Aug 21 19:31 rc6.d
drwxr-xr-x 2 root root    4096 Aug 12 00:00 rcS.d
-rw-r--r-- 1 root root      38 Aug 21 19:30 resolv.conf
lrwxrwxrwx 1 root root      13 Apr 23 16:05 rmt -> /usr/sbin/rmt
-rw-r--r-- 1 root root    4141 Jul 27  2018 securetty
drwxr-xr-x 4 root root    4096 Aug 12 00:00 security
drwxr-xr-x 2 root root    4096 Aug 12 00:00 selinux
-rw-r----- 1 root shadow   501 Aug 12 00:00 shadow
-rw-r----- 1 root shadow   501 Aug 12 00:00 shadow-
-rw-r--r-- 1 root root      73 Aug 12 00:00 shells
drwxr-xr-x 2 root root    4096 Aug 12 00:00 skel
drwxr-xr-x 4 root root    4096 Aug 14 07:31 ssl
-rw-r--r-- 1 root root       0 Aug 12 00:00 subgid
-rw-r--r-- 1 root root       0 Aug 12 00:00 subuid
drwxr-xr-x 1 root root    4096 Dec  3  2018 systemd
drwxr-xr-x 2 root root    4096 Aug 12 00:00 terminfo
-rw-r--r-- 1 root root       8 Aug 12 00:00 timezone
-rw-r--r-- 1 root root    1260 Dec 14  2018 ucf.conf
drwxr-xr-x 3 root root    4096 Aug 21 19:31 ufw
drwxr-xr-x 2 root root    4096 Aug 12 00:00 update-motd.d
-rw-r--r-- 1 root root     642 Mar  1 22:03 xattr.conf
```

**Comment by StefanieD** [comment]
Hi,
is your nginx container running? After `docker-compose up -d` , check with `docker-compose ps` if the container nginx was build successfully.
Actually the nginx image has always a default site config under this path.

Is your output from your nginx container?

**Comment by alex-w0** [comment]
Hi, the container nginx is build successfully. I noticed now that I entered the wrong container, so the default.conf is generated successfully.

Nevertheless, I get a number of errors when I call http://localhost:8080/ . Any ideas what could be the problem? Thanks :)

![image](https://user-images.githubusercontent.com/25109632/63527513-85af2d00-c501-11e9-9877-d088eaf9eed8.png)

**Edited:** Found now the issue an additional configuration in the site.conf was missing https://pimcore.com/docs/5.x/Development_Documentation/Installation_and_Upgrade/System_Setup_and_Hosting/Nginx_Configuration.html
`# rewrite ^/cache-buster-(?:\d+)/(.*) /$1 last;`

Btw. another improvement for your readme, I had to append to the command `bin/console assets:install` also the destination directory `bin/console assets:install web`

**Comment by StefanieD** [comment]
You're totally right. I've updated the site.conf and the README files.

**Comment by alex-w0** [comment]
Great thanks :)

Another problem: for some reason the images (in the frontend and also in the backend) are not displayed correctly. The directory /web/var/tmp/image-thumbnails has no files.

![image](https://user-images.githubusercontent.com/25109632/63611691-c0d25e80-c5dc-11e9-92a3-37ab56193089.png)

**Comment by StefanieD** [comment]
I've found the problem. For generating thumbnails imagick needs to be installed. I've updated the Dockerfile.
After rebuilding the container you can run `php bin/console pimcore:thumbnails:image`. All Thumbnails will be created under `/web/var/tmp/image-thumbnails`.

After that, make sure that you set the right permissions for `/web/var`. I've just set `/web/var' to 755. 

Then you should be able to see the thumbnails in frontend and the previews in admin panels.

**Comment by alex-w0** [comment]
Hi, unfortunately it's still not working. No thumbnails were generated inside /web/var/tmp/image-thumbnails. All folders are empty, even if I updated the php dockerfile and executed `php bin/console pimcore:thumbnails:image`

**Comment by StefanieD** [comment]
Did you build your container new? With `docker-compose build`?

**Comment by alex-w0** [comment]
Yes i did the following `docker-compose build --no-cache nginx php`

I tried now to completely reinstall the application, but also there I'm receiving now some errors. Have some new PHP extensions been added to the package?

![image](https://user-images.githubusercontent.com/25109632/63957723-421c6c00-ca89-11e9-8ebf-2662a8329ab8.png)

**Comment by StefanieD** [comment]
Yeah my fault. I've deleted the gd extension in Dockerfile.
I've enabled it again. Try build and thumbnail generation again.

**Comment by alex-w0** [comment]
When I tried to reinstall pimcore and I follow your readme instructions, it gives me the following error message on the command

`
cd pimcore && COMPOSER_MEMORY_LIMIT=-1 ./vendor/bin/pimcore-install \ --admin-username=admin --admin-password=admin --mysql-host-socket=mysql \ --mysql-username=pimcore --mysql-password=pimcore --mysql-database=pimcore --no-interaction
`

![image](https://user-images.githubusercontent.com/25109632/64064059-410c4b80-cbfd-11e9-97dd-01559255d927.png)

**Comment by StefanieD** [comment]
Hey, 
this is just because of the backslashes \ . Remove them from the command. Seems like the console can not read it correctly when you copy and paste it.

I've reverted this change in the README file.

**Comment by alex-w0** [comment]
Hi, it's working now. Thanks for the help :)
