### ISSUE TITLE
Fatal error: Allowed memory size ... exhausted ...

### ISSUE THREAD

**Issue by RaphOb** [StefanieD/pimcore-docker-setup#4]
hi
on localhost:8080 i got this :`Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/pimcore/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 107`

First i thought the issue was in php.ini, but seems not.
Any idea ?
thank you

**Comment by StefanieD** [comment]
Hi,
can you look into the logs for more information? You should find your dev log in your php conatiner.

**Comment by RaphOb** [comment]
I set memory_limit = -1 to check and it return me a 502.

> nginx_1  | 172.22.0.1 - - [30/Aug/2019:14:48:02 +0000] "GET / HTTP/1.1" 502 157 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0" "-"
php_1    | [30-Aug-2019 14:48:02] WARNING: [pool www] child 12 exited on signal 9 (SIGKILL) after 794.522278 seconds from start
php_1    | [30-Aug-2019 14:48:02] NOTICE: [pool www] child 46 started


I cant find any php log in php container
thank you

**Comment by StefanieD** [comment]
When you go into your php container with `docker-compose exec php bash`
you'll find your logs under `/var/www/html/pimcore/var/log/dev.log`

It seems that Monolog tries to log something. An error message would be helpful.
Basically you need to set the memory limit in the php-fpm ini.
